# Generated by Django 4.0.3 on 2022-03-23 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.CharField(default='', max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='user.patient')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user.professional')),
            ],
        ),
    ]
