# Generated by Django 4.0.3 on 2022-03-26 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='username',
            new_name='password',
        ),
    ]
